# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io/ - Email: support@spatialflow.io     

    The version of the OpenAPI document: v1.36.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ActionDeliveryOut(BaseModel):
    """
    Per-step delivery outcome for a WorkflowExecution step.
    """ # noqa: E501
    step_index: StrictInt
    node_id: Optional[StrictStr] = None
    step_type: StrictStr
    step_name: StrictStr
    step_status: StrictStr
    delivery_status: Optional[StrictStr] = None
    error_message: Optional[StrictStr] = None
    condition_passed: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["step_index", "node_id", "step_type", "step_name", "step_status", "delivery_status", "error_message", "condition_passed"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActionDeliveryOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if node_id (nullable) is None
        # and model_fields_set contains the field
        if self.node_id is None and "node_id" in self.model_fields_set:
            _dict['node_id'] = None

        # set to None if delivery_status (nullable) is None
        # and model_fields_set contains the field
        if self.delivery_status is None and "delivery_status" in self.model_fields_set:
            _dict['delivery_status'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['error_message'] = None

        # set to None if condition_passed (nullable) is None
        # and model_fields_set contains the field
        if self.condition_passed is None and "condition_passed" in self.model_fields_set:
            _dict['condition_passed'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActionDeliveryOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "step_index": obj.get("step_index"),
            "node_id": obj.get("node_id"),
            "step_type": obj.get("step_type"),
            "step_name": obj.get("step_name"),
            "step_status": obj.get("step_status"),
            "delivery_status": obj.get("delivery_status"),
            "error_message": obj.get("error_message"),
            "condition_passed": obj.get("condition_passed")
        })
        return _obj


