# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Per API Key: 200 rps sustained, 1,000 rps burst - Per Organization: 1,000 rps aggregate  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from .circuit_breaker_schema import CircuitBreakerSchema
from .retry_policy_schema import RetryPolicySchema
from typing import Optional, Set
from typing_extensions import Self

class ActionRetryConfigSchema(BaseModel):
    """
    Complete retry configuration for an action.
    """ # noqa: E501
    retry_policy: Optional[RetryPolicySchema] = None
    circuit_breaker: Optional[CircuitBreakerSchema] = None
    retry_policy_name: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["retry_policy", "circuit_breaker", "retry_policy_name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActionRetryConfigSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of retry_policy
        if self.retry_policy:
            _dict['retry_policy'] = self.retry_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of circuit_breaker
        if self.circuit_breaker:
            _dict['circuit_breaker'] = self.circuit_breaker.to_dict()
        # set to None if retry_policy (nullable) is None
        # and model_fields_set contains the field
        if self.retry_policy is None and "retry_policy" in self.model_fields_set:
            _dict['retry_policy'] = None

        # set to None if circuit_breaker (nullable) is None
        # and model_fields_set contains the field
        if self.circuit_breaker is None and "circuit_breaker" in self.model_fields_set:
            _dict['circuit_breaker'] = None

        # set to None if retry_policy_name (nullable) is None
        # and model_fields_set contains the field
        if self.retry_policy_name is None and "retry_policy_name" in self.model_fields_set:
            _dict['retry_policy_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActionRetryConfigSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "retry_policy": RetryPolicySchema.from_dict(obj["retry_policy"]) if obj.get("retry_policy") is not None else None,
            "circuit_breaker": CircuitBreakerSchema.from_dict(obj["circuit_breaker"]) if obj.get("circuit_breaker") is not None else None,
            "retry_policy_name": obj.get("retry_policy_name")
        })
        return _obj


