# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io/ - Email: support@spatialflow.io     

    The version of the OpenAPI document: v1.36.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DashboardStatsOut(BaseModel):
    """
    DashboardStatsOut
    """ # noqa: E501
    active_device_count: StrictInt
    live_count: StrictInt
    reporting_count: StrictInt
    offline_stale_count: StrictInt
    expected_reporting_count: StrictInt
    attention_count: StrictInt
    parked_count: StrictInt
    reporting_window_minutes: StrictInt
    paused_count: StrictInt
    off_shift_count: StrictInt
    low_battery_count: StrictInt
    low_battery_window_minutes: StrictInt
    in_geofence_count: StrictInt
    last_known_geofence_count: StrictInt
    confirmed_current_geofence_count: StrictInt
    alerts_open: StrictInt
    workflow_failures_1h: Optional[StrictInt] = None
    webhook_retries_1h: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["active_device_count", "live_count", "reporting_count", "offline_stale_count", "expected_reporting_count", "attention_count", "parked_count", "reporting_window_minutes", "paused_count", "off_shift_count", "low_battery_count", "low_battery_window_minutes", "in_geofence_count", "last_known_geofence_count", "confirmed_current_geofence_count", "alerts_open", "workflow_failures_1h", "webhook_retries_1h"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DashboardStatsOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if workflow_failures_1h (nullable) is None
        # and model_fields_set contains the field
        if self.workflow_failures_1h is None and "workflow_failures_1h" in self.model_fields_set:
            _dict['workflow_failures_1h'] = None

        # set to None if webhook_retries_1h (nullable) is None
        # and model_fields_set contains the field
        if self.webhook_retries_1h is None and "webhook_retries_1h" in self.model_fields_set:
            _dict['webhook_retries_1h'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DashboardStatsOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active_device_count": obj.get("active_device_count"),
            "live_count": obj.get("live_count"),
            "reporting_count": obj.get("reporting_count"),
            "offline_stale_count": obj.get("offline_stale_count"),
            "expected_reporting_count": obj.get("expected_reporting_count"),
            "attention_count": obj.get("attention_count"),
            "parked_count": obj.get("parked_count"),
            "reporting_window_minutes": obj.get("reporting_window_minutes"),
            "paused_count": obj.get("paused_count"),
            "off_shift_count": obj.get("off_shift_count"),
            "low_battery_count": obj.get("low_battery_count"),
            "low_battery_window_minutes": obj.get("low_battery_window_minutes"),
            "in_geofence_count": obj.get("in_geofence_count"),
            "last_known_geofence_count": obj.get("last_known_geofence_count"),
            "confirmed_current_geofence_count": obj.get("confirmed_current_geofence_count"),
            "alerts_open": obj.get("alerts_open"),
            "workflow_failures_1h": obj.get("workflow_failures_1h"),
            "webhook_retries_1h": obj.get("webhook_retries_1h")
        })
        return _obj


