# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

    The version of the OpenAPI document: v1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from .lat_lon_out import LatLonOut
from typing import Optional, Set
from typing_extensions import Self

class DeviceOut(BaseModel):
    """
    DeviceOut
    """ # noqa: E501
    id: StrictStr
    device_id: StrictStr
    name: StrictStr
    device_type: StrictStr
    is_active: StrictBool
    shift_status: StrictStr
    shift_started_at: Optional[datetime] = None
    shift_paused_at: Optional[datetime] = None
    shift_ended_at: Optional[datetime] = None
    shift_resumed_at: Optional[datetime] = None
    last_location: Optional[LatLonOut] = None
    last_location_time: Optional[datetime] = None
    last_heading: Optional[Union[StrictFloat, StrictInt]] = None
    current_session_notes: Optional[StrictStr] = ''
    in_geofence_ids: Optional[List[StrictStr]] = None
    in_geofence_entries: Optional[Dict[str, StrictStr]] = None
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["id", "device_id", "name", "device_type", "is_active", "shift_status", "shift_started_at", "shift_paused_at", "shift_ended_at", "shift_resumed_at", "last_location", "last_location_time", "last_heading", "current_session_notes", "in_geofence_ids", "in_geofence_entries", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeviceOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of last_location
        if self.last_location:
            _dict['last_location'] = self.last_location.to_dict()
        # set to None if shift_started_at (nullable) is None
        # and model_fields_set contains the field
        if self.shift_started_at is None and "shift_started_at" in self.model_fields_set:
            _dict['shift_started_at'] = None

        # set to None if shift_paused_at (nullable) is None
        # and model_fields_set contains the field
        if self.shift_paused_at is None and "shift_paused_at" in self.model_fields_set:
            _dict['shift_paused_at'] = None

        # set to None if shift_ended_at (nullable) is None
        # and model_fields_set contains the field
        if self.shift_ended_at is None and "shift_ended_at" in self.model_fields_set:
            _dict['shift_ended_at'] = None

        # set to None if shift_resumed_at (nullable) is None
        # and model_fields_set contains the field
        if self.shift_resumed_at is None and "shift_resumed_at" in self.model_fields_set:
            _dict['shift_resumed_at'] = None

        # set to None if last_location (nullable) is None
        # and model_fields_set contains the field
        if self.last_location is None and "last_location" in self.model_fields_set:
            _dict['last_location'] = None

        # set to None if last_location_time (nullable) is None
        # and model_fields_set contains the field
        if self.last_location_time is None and "last_location_time" in self.model_fields_set:
            _dict['last_location_time'] = None

        # set to None if last_heading (nullable) is None
        # and model_fields_set contains the field
        if self.last_heading is None and "last_heading" in self.model_fields_set:
            _dict['last_heading'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeviceOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "device_id": obj.get("device_id"),
            "name": obj.get("name"),
            "device_type": obj.get("device_type"),
            "is_active": obj.get("is_active"),
            "shift_status": obj.get("shift_status"),
            "shift_started_at": obj.get("shift_started_at"),
            "shift_paused_at": obj.get("shift_paused_at"),
            "shift_ended_at": obj.get("shift_ended_at"),
            "shift_resumed_at": obj.get("shift_resumed_at"),
            "last_location": LatLonOut.from_dict(obj["last_location"]) if obj.get("last_location") is not None else None,
            "last_location_time": obj.get("last_location_time"),
            "last_heading": obj.get("last_heading"),
            "current_session_notes": obj.get("current_session_notes") if obj.get("current_session_notes") is not None else '',
            "in_geofence_ids": obj.get("in_geofence_ids"),
            "in_geofence_entries": obj.get("in_geofence_entries"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


