# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io/ - Email: support@spatialflow.io     

    The version of the OpenAPI document: v1.36.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class IncidentOut(BaseModel):
    """
    IncidentOut
    """ # noqa: E501
    id: StrictStr
    signal_type: StrictStr
    source_ids: List[StrictStr]
    severity: StrictStr
    opened_at: datetime
    acknowledged_at: Optional[datetime] = None
    acknowledged_by: Optional[StrictStr] = None
    muted_until: Optional[datetime] = None
    owner_id: Optional[StrictStr] = None
    resolved_at: Optional[datetime] = None
    payload: Dict[str, Any]
    status: StrictStr
    __properties: ClassVar[List[str]] = ["id", "signal_type", "source_ids", "severity", "opened_at", "acknowledged_at", "acknowledged_by", "muted_until", "owner_id", "resolved_at", "payload", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IncidentOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if acknowledged_at (nullable) is None
        # and model_fields_set contains the field
        if self.acknowledged_at is None and "acknowledged_at" in self.model_fields_set:
            _dict['acknowledged_at'] = None

        # set to None if acknowledged_by (nullable) is None
        # and model_fields_set contains the field
        if self.acknowledged_by is None and "acknowledged_by" in self.model_fields_set:
            _dict['acknowledged_by'] = None

        # set to None if muted_until (nullable) is None
        # and model_fields_set contains the field
        if self.muted_until is None and "muted_until" in self.model_fields_set:
            _dict['muted_until'] = None

        # set to None if owner_id (nullable) is None
        # and model_fields_set contains the field
        if self.owner_id is None and "owner_id" in self.model_fields_set:
            _dict['owner_id'] = None

        # set to None if resolved_at (nullable) is None
        # and model_fields_set contains the field
        if self.resolved_at is None and "resolved_at" in self.model_fields_set:
            _dict['resolved_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IncidentOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "signal_type": obj.get("signal_type"),
            "source_ids": obj.get("source_ids"),
            "severity": obj.get("severity"),
            "opened_at": obj.get("opened_at"),
            "acknowledged_at": obj.get("acknowledged_at"),
            "acknowledged_by": obj.get("acknowledged_by"),
            "muted_until": obj.get("muted_until"),
            "owner_id": obj.get("owner_id"),
            "resolved_at": obj.get("resolved_at"),
            "payload": obj.get("payload"),
            "status": obj.get("status")
        })
        return _obj


