# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Per API Key: 200 rps sustained, 1,000 rps burst - Per Organization: 1,000 rps aggregate  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class IntegrationTypeRequest(BaseModel):
    """
    Request schema for creating/updating integration types
    """ # noqa: E501
    key: StrictStr = Field(description="Unique identifier for this integration type")
    name: StrictStr = Field(description="Display name for this integration type")
    description: StrictStr = Field(description="User-friendly description")
    icon: Optional[StrictStr] = Field(default='default', description="Icon identifier for UI display")
    category: Optional[StrictStr] = Field(default='general', description="Category: general, communication, cloud, analytics, automation, custom")
    handler_class: StrictStr = Field(description="Python path to the action handler class")
    validator_class: Optional[StrictStr] = None
    oauth_enabled: Optional[StrictBool] = Field(default=False, description="Whether this integration supports OAuth authentication")
    oauth_config: Optional[Dict[str, Any]] = Field(default=None, description="OAuth configuration")
    documentation_url: Optional[StrictStr] = None
    is_active: Optional[StrictBool] = Field(default=True, description="Whether this integration type is available for use")
    __properties: ClassVar[List[str]] = ["key", "name", "description", "icon", "category", "handler_class", "validator_class", "oauth_enabled", "oauth_config", "documentation_url", "is_active"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntegrationTypeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if validator_class (nullable) is None
        # and model_fields_set contains the field
        if self.validator_class is None and "validator_class" in self.model_fields_set:
            _dict['validator_class'] = None

        # set to None if documentation_url (nullable) is None
        # and model_fields_set contains the field
        if self.documentation_url is None and "documentation_url" in self.model_fields_set:
            _dict['documentation_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntegrationTypeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "key": obj.get("key"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "icon": obj.get("icon") if obj.get("icon") is not None else 'default',
            "category": obj.get("category") if obj.get("category") is not None else 'general',
            "handler_class": obj.get("handler_class"),
            "validator_class": obj.get("validator_class"),
            "oauth_enabled": obj.get("oauth_enabled") if obj.get("oauth_enabled") is not None else False,
            "oauth_config": obj.get("oauth_config"),
            "documentation_url": obj.get("documentation_url"),
            "is_active": obj.get("is_active") if obj.get("is_active") is not None else True
        })
        return _obj


