# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Per API Key: 200 rps sustained, 1,000 rps burst - Per Organization: 1,000 rps aggregate  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class IntegrationTypeResponse(BaseModel):
    """
    Response schema for IntegrationType
    """ # noqa: E501
    id: StrictStr
    key: StrictStr
    name: StrictStr
    description: StrictStr
    icon: StrictStr
    category: StrictStr
    handler_class: StrictStr
    validator_class: Optional[StrictStr]
    is_active: StrictBool
    is_builtin: StrictBool
    oauth_enabled: StrictBool
    oauth_config: Dict[str, Any]
    documentation_url: Optional[StrictStr]
    created_at: datetime
    updated_at: datetime
    config_fields_count: Optional[StrictInt] = 0
    __properties: ClassVar[List[str]] = ["id", "key", "name", "description", "icon", "category", "handler_class", "validator_class", "is_active", "is_builtin", "oauth_enabled", "oauth_config", "documentation_url", "created_at", "updated_at", "config_fields_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntegrationTypeResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if validator_class (nullable) is None
        # and model_fields_set contains the field
        if self.validator_class is None and "validator_class" in self.model_fields_set:
            _dict['validator_class'] = None

        # set to None if documentation_url (nullable) is None
        # and model_fields_set contains the field
        if self.documentation_url is None and "documentation_url" in self.model_fields_set:
            _dict['documentation_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntegrationTypeResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "key": obj.get("key"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "icon": obj.get("icon"),
            "category": obj.get("category"),
            "handler_class": obj.get("handler_class"),
            "validator_class": obj.get("validator_class"),
            "is_active": obj.get("is_active"),
            "is_builtin": obj.get("is_builtin"),
            "oauth_enabled": obj.get("oauth_enabled"),
            "oauth_config": obj.get("oauth_config"),
            "documentation_url": obj.get("documentation_url"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "config_fields_count": obj.get("config_fields_count") if obj.get("config_fields_count") is not None else 0
        })
        return _obj


