# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io/ - Email: support@spatialflow.io     

    The version of the OpenAPI document: v1.36.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class InvitationIssuedOut(BaseModel):
    """
    Response for the two endpoints that MINT a token: create and resend.  Carries `invite_link` -- byte for byte the same link the invitation email contains -- so the caller who just created the invitation can render it as a QR code for on-site check-in without a second token transport. The token is stored hashed and is unrecoverable afterwards, which is why the listing schema deliberately still omits it: `InvitationOut` never exposes a token, and only the authenticated owner/manager making this very request sees it.
    """ # noqa: E501
    id: StrictStr
    email: StrictStr
    role: StrictStr
    status: StrictStr
    created_at: datetime
    expires_at: datetime
    invited_by_email: Optional[StrictStr] = None
    invite_link: StrictStr
    invite_ttl_hours: StrictInt
    __properties: ClassVar[List[str]] = ["id", "email", "role", "status", "created_at", "expires_at", "invited_by_email", "invite_link", "invite_ttl_hours"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvitationIssuedOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if invited_by_email (nullable) is None
        # and model_fields_set contains the field
        if self.invited_by_email is None and "invited_by_email" in self.model_fields_set:
            _dict['invited_by_email'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvitationIssuedOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "email": obj.get("email"),
            "role": obj.get("role"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "expires_at": obj.get("expires_at"),
            "invited_by_email": obj.get("invited_by_email"),
            "invite_link": obj.get("invite_link"),
            "invite_ttl_hours": obj.get("invite_ttl_hours")
        })
        return _obj


