# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Per API Key: 200 rps sustained, 1,000 rps burst - Per Organization: 1,000 rps aggregate  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from .invoice_line_item import InvoiceLineItem
from typing import Optional, Set
from typing_extensions import Self

class InvoiceResponse(BaseModel):
    """
    Invoice details.
    """ # noqa: E501
    id: StrictStr
    number: StrictStr
    status: StrictStr
    amount_due: StrictInt
    amount_paid: StrictInt
    currency: StrictStr
    period_start: StrictInt
    period_end: StrictInt
    created_at: StrictInt
    invoice_pdf: Optional[StrictStr] = None
    line_items: List[InvoiceLineItem]
    __properties: ClassVar[List[str]] = ["id", "number", "status", "amount_due", "amount_paid", "currency", "period_start", "period_end", "created_at", "invoice_pdf", "line_items"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvoiceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in line_items (list)
        _items = []
        if self.line_items:
            for _item_line_items in self.line_items:
                if _item_line_items:
                    _items.append(_item_line_items.to_dict())
            _dict['line_items'] = _items
        # set to None if invoice_pdf (nullable) is None
        # and model_fields_set contains the field
        if self.invoice_pdf is None and "invoice_pdf" in self.model_fields_set:
            _dict['invoice_pdf'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvoiceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "number": obj.get("number"),
            "status": obj.get("status"),
            "amount_due": obj.get("amount_due"),
            "amount_paid": obj.get("amount_paid"),
            "currency": obj.get("currency"),
            "period_start": obj.get("period_start"),
            "period_end": obj.get("period_end"),
            "created_at": obj.get("created_at"),
            "invoice_pdf": obj.get("invoice_pdf"),
            "line_items": [InvoiceLineItem.from_dict(_item) for _item in obj["line_items"]] if obj.get("line_items") is not None else None
        })
        return _obj


