# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io/ - Email: support@spatialflow.io     

    The version of the OpenAPI document: v1.36.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class IssueReportRequest(BaseModel):
    """
    Private in-app issue report submission.
    """ # noqa: E501
    area: Optional[Annotated[str, Field(strict=True, max_length=80)]] = 'Other'
    title: Optional[Annotated[str, Field(strict=True, max_length=160)]] = None
    description: Annotated[str, Field(strict=True, max_length=4000)]
    steps: Optional[Annotated[str, Field(strict=True, max_length=4000)]] = None
    expected: Optional[Annotated[str, Field(strict=True, max_length=4000)]] = None
    include_diagnostics: Optional[StrictBool] = True
    include_page: Optional[StrictBool] = True
    include_browser: Optional[StrictBool] = True
    include_version: Optional[StrictBool] = True
    diagnostics: Optional[Dict[str, Any]] = None
    page_url: Optional[Annotated[str, Field(strict=True, max_length=2000)]] = None
    browser: Optional[Dict[str, Any]] = None
    app_version: Optional[Annotated[str, Field(strict=True, max_length=80)]] = None
    __properties: ClassVar[List[str]] = ["area", "title", "description", "steps", "expected", "include_diagnostics", "include_page", "include_browser", "include_version", "diagnostics", "page_url", "browser", "app_version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IssueReportRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if steps (nullable) is None
        # and model_fields_set contains the field
        if self.steps is None and "steps" in self.model_fields_set:
            _dict['steps'] = None

        # set to None if expected (nullable) is None
        # and model_fields_set contains the field
        if self.expected is None and "expected" in self.model_fields_set:
            _dict['expected'] = None

        # set to None if page_url (nullable) is None
        # and model_fields_set contains the field
        if self.page_url is None and "page_url" in self.model_fields_set:
            _dict['page_url'] = None

        # set to None if app_version (nullable) is None
        # and model_fields_set contains the field
        if self.app_version is None and "app_version" in self.model_fields_set:
            _dict['app_version'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IssueReportRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "area": obj.get("area") if obj.get("area") is not None else 'Other',
            "title": obj.get("title"),
            "description": obj.get("description"),
            "steps": obj.get("steps"),
            "expected": obj.get("expected"),
            "include_diagnostics": obj.get("include_diagnostics") if obj.get("include_diagnostics") is not None else True,
            "include_page": obj.get("include_page") if obj.get("include_page") is not None else True,
            "include_browser": obj.get("include_browser") if obj.get("include_browser") is not None else True,
            "include_version": obj.get("include_version") if obj.get("include_version") is not None else True,
            "diagnostics": obj.get("diagnostics"),
            "page_url": obj.get("page_url"),
            "browser": obj.get("browser"),
            "app_version": obj.get("app_version")
        })
        return _obj


