# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

    The version of the OpenAPI document: v1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class NotificationConfigUpdateRequest(BaseModel):
    """
    Request to update notification configuration.  Provider switching rules: - If provider changes and webhook_url is not provided, the existing webhook_url is cleared - webhook_url must match the pattern for the target provider
    """ # noqa: E501
    provider: Optional[StrictStr] = None
    webhook_url: Optional[StrictStr] = None
    is_enabled: Optional[StrictBool] = None
    notify_new_signups: Optional[StrictBool] = None
    notify_admin_approvals: Optional[StrictBool] = None
    notify_subscription_changes: Optional[StrictBool] = None
    notify_payment_failures: Optional[StrictBool] = None
    notify_privacy_erasures: Optional[StrictBool] = None
    notify_dlq_threshold: Optional[StrictBool] = None
    notify_service_health: Optional[StrictBool] = None
    dlq_threshold: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["provider", "webhook_url", "is_enabled", "notify_new_signups", "notify_admin_approvals", "notify_subscription_changes", "notify_payment_failures", "notify_privacy_erasures", "notify_dlq_threshold", "notify_service_health", "dlq_threshold"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NotificationConfigUpdateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if provider (nullable) is None
        # and model_fields_set contains the field
        if self.provider is None and "provider" in self.model_fields_set:
            _dict['provider'] = None

        # set to None if webhook_url (nullable) is None
        # and model_fields_set contains the field
        if self.webhook_url is None and "webhook_url" in self.model_fields_set:
            _dict['webhook_url'] = None

        # set to None if is_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.is_enabled is None and "is_enabled" in self.model_fields_set:
            _dict['is_enabled'] = None

        # set to None if notify_new_signups (nullable) is None
        # and model_fields_set contains the field
        if self.notify_new_signups is None and "notify_new_signups" in self.model_fields_set:
            _dict['notify_new_signups'] = None

        # set to None if notify_admin_approvals (nullable) is None
        # and model_fields_set contains the field
        if self.notify_admin_approvals is None and "notify_admin_approvals" in self.model_fields_set:
            _dict['notify_admin_approvals'] = None

        # set to None if notify_subscription_changes (nullable) is None
        # and model_fields_set contains the field
        if self.notify_subscription_changes is None and "notify_subscription_changes" in self.model_fields_set:
            _dict['notify_subscription_changes'] = None

        # set to None if notify_payment_failures (nullable) is None
        # and model_fields_set contains the field
        if self.notify_payment_failures is None and "notify_payment_failures" in self.model_fields_set:
            _dict['notify_payment_failures'] = None

        # set to None if notify_privacy_erasures (nullable) is None
        # and model_fields_set contains the field
        if self.notify_privacy_erasures is None and "notify_privacy_erasures" in self.model_fields_set:
            _dict['notify_privacy_erasures'] = None

        # set to None if notify_dlq_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.notify_dlq_threshold is None and "notify_dlq_threshold" in self.model_fields_set:
            _dict['notify_dlq_threshold'] = None

        # set to None if notify_service_health (nullable) is None
        # and model_fields_set contains the field
        if self.notify_service_health is None and "notify_service_health" in self.model_fields_set:
            _dict['notify_service_health'] = None

        # set to None if dlq_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.dlq_threshold is None and "dlq_threshold" in self.model_fields_set:
            _dict['dlq_threshold'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NotificationConfigUpdateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "provider": obj.get("provider"),
            "webhook_url": obj.get("webhook_url"),
            "is_enabled": obj.get("is_enabled"),
            "notify_new_signups": obj.get("notify_new_signups"),
            "notify_admin_approvals": obj.get("notify_admin_approvals"),
            "notify_subscription_changes": obj.get("notify_subscription_changes"),
            "notify_payment_failures": obj.get("notify_payment_failures"),
            "notify_privacy_erasures": obj.get("notify_privacy_erasures"),
            "notify_dlq_threshold": obj.get("notify_dlq_threshold"),
            "notify_service_health": obj.get("notify_service_health"),
            "dlq_threshold": obj.get("dlq_threshold")
        })
        return _obj


