# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

    The version of the OpenAPI document: v1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PlanLimits(BaseModel):
    """
    Usage limits for a subscription plan.
    """ # noqa: E501
    api_calls: StrictInt = Field(description="Monthly API call limit (-1 for unlimited)")
    geofences: StrictInt = Field(description="Maximum number of geofences (-1 for unlimited)")
    webhooks_delivered: StrictInt = Field(description="Monthly webhook delivery limit (-1 for unlimited)")
    test_points: StrictInt = Field(description="Monthly test point limit (-1 for unlimited)")
    rate_limit_per_hour: StrictInt = Field(description="Hourly rate limit")
    log_retention_days: Optional[StrictInt] = Field(default=7, description="Log retention in days (-1 for unlimited)")
    location_retention_days: Optional[StrictInt] = Field(default=90, description="Location data retention in days")
    __properties: ClassVar[List[str]] = ["api_calls", "geofences", "webhooks_delivered", "test_points", "rate_limit_per_hour", "log_retention_days", "location_retention_days"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlanLimits from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlanLimits from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_calls": obj.get("api_calls"),
            "geofences": obj.get("geofences"),
            "webhooks_delivered": obj.get("webhooks_delivered"),
            "test_points": obj.get("test_points"),
            "rate_limit_per_hour": obj.get("rate_limit_per_hour"),
            "log_retention_days": obj.get("log_retention_days") if obj.get("log_retention_days") is not None else 7,
            "location_retention_days": obj.get("location_retention_days") if obj.get("location_retention_days") is not None else 90
        })
        return _obj


