# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Per API Key: 200 rps sustained, 1,000 rps burst - Per Organization: 1,000 rps aggregate  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from .delivery_status_enum import DeliveryStatusEnum
from typing import Optional, Set
from typing_extensions import Self

class WebhookDeliveryResponse(BaseModel):
    """
    Schema for webhook delivery response
    """ # noqa: E501
    id: StrictStr
    webhook_id: Optional[StrictStr]
    geofence_id: Optional[StrictStr]
    event_type: StrictStr
    event_id: StrictStr
    url: StrictStr
    method: StrictStr
    status: DeliveryStatusEnum
    response_status_code: Optional[StrictInt]
    response_status: Optional[StrictInt] = None
    response_time_ms: Optional[Union[StrictFloat, StrictInt]]
    error_message: Optional[StrictStr]
    attempt_count: StrictInt
    retry_count: Optional[StrictInt] = 0
    created_at: datetime
    delivered_at: Optional[datetime]
    next_retry_at: Optional[datetime]
    __properties: ClassVar[List[str]] = ["id", "webhook_id", "geofence_id", "event_type", "event_id", "url", "method", "status", "response_status_code", "response_status", "response_time_ms", "error_message", "attempt_count", "retry_count", "created_at", "delivered_at", "next_retry_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookDeliveryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if webhook_id (nullable) is None
        # and model_fields_set contains the field
        if self.webhook_id is None and "webhook_id" in self.model_fields_set:
            _dict['webhook_id'] = None

        # set to None if geofence_id (nullable) is None
        # and model_fields_set contains the field
        if self.geofence_id is None and "geofence_id" in self.model_fields_set:
            _dict['geofence_id'] = None

        # set to None if response_status_code (nullable) is None
        # and model_fields_set contains the field
        if self.response_status_code is None and "response_status_code" in self.model_fields_set:
            _dict['response_status_code'] = None

        # set to None if response_status (nullable) is None
        # and model_fields_set contains the field
        if self.response_status is None and "response_status" in self.model_fields_set:
            _dict['response_status'] = None

        # set to None if response_time_ms (nullable) is None
        # and model_fields_set contains the field
        if self.response_time_ms is None and "response_time_ms" in self.model_fields_set:
            _dict['response_time_ms'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['error_message'] = None

        # set to None if delivered_at (nullable) is None
        # and model_fields_set contains the field
        if self.delivered_at is None and "delivered_at" in self.model_fields_set:
            _dict['delivered_at'] = None

        # set to None if next_retry_at (nullable) is None
        # and model_fields_set contains the field
        if self.next_retry_at is None and "next_retry_at" in self.model_fields_set:
            _dict['next_retry_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookDeliveryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "webhook_id": obj.get("webhook_id"),
            "geofence_id": obj.get("geofence_id"),
            "event_type": obj.get("event_type"),
            "event_id": obj.get("event_id"),
            "url": obj.get("url"),
            "method": obj.get("method"),
            "status": obj.get("status"),
            "response_status_code": obj.get("response_status_code"),
            "response_status": obj.get("response_status"),
            "response_time_ms": obj.get("response_time_ms"),
            "error_message": obj.get("error_message"),
            "attempt_count": obj.get("attempt_count"),
            "retry_count": obj.get("retry_count") if obj.get("retry_count") is not None else 0,
            "created_at": obj.get("created_at"),
            "delivered_at": obj.get("delivered_at"),
            "next_retry_at": obj.get("next_retry_at")
        })
        return _obj


