# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Per API Key: 200 rps sustained, 1,000 rps burst - Per Organization: 1,000 rps aggregate  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from .template_warnings import TemplateWarnings
from typing import Optional, Set
from typing_extensions import Self

class WorkflowOut(BaseModel):
    """
    WorkflowOut
    """ # noqa: E501
    id: UUID
    name: StrictStr
    description: Optional[StrictStr]
    status: StrictStr
    nodes: List[Optional[Dict[str, Any]]]
    edges: List[Optional[Dict[str, Any]]]
    created_at: datetime
    updated_at: datetime
    last_run: Optional[StrictStr]
    run_count: StrictInt
    success_rate: Union[StrictFloat, StrictInt]
    user_id: StrictStr
    workspace_id: Optional[StrictStr] = None
    version: StrictInt
    template_warnings: Optional[TemplateWarnings] = None
    __properties: ClassVar[List[str]] = ["id", "name", "description", "status", "nodes", "edges", "created_at", "updated_at", "last_run", "run_count", "success_rate", "user_id", "workspace_id", "version", "template_warnings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of template_warnings
        if self.template_warnings:
            _dict['template_warnings'] = self.template_warnings.to_dict()
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if last_run (nullable) is None
        # and model_fields_set contains the field
        if self.last_run is None and "last_run" in self.model_fields_set:
            _dict['last_run'] = None

        # set to None if workspace_id (nullable) is None
        # and model_fields_set contains the field
        if self.workspace_id is None and "workspace_id" in self.model_fields_set:
            _dict['workspace_id'] = None

        # set to None if template_warnings (nullable) is None
        # and model_fields_set contains the field
        if self.template_warnings is None and "template_warnings" in self.model_fields_set:
            _dict['template_warnings'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "nodes": obj.get("nodes"),
            "edges": obj.get("edges"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "last_run": obj.get("last_run"),
            "run_count": obj.get("run_count"),
            "success_rate": obj.get("success_rate"),
            "user_id": obj.get("user_id"),
            "workspace_id": obj.get("workspace_id"),
            "version": obj.get("version"),
            "template_warnings": TemplateWarnings.from_dict(obj["template_warnings"]) if obj.get("template_warnings") is not None else None
        })
        return _obj


