# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io/ - Email: support@spatialflow.io     

    The version of the OpenAPI document: v1.36.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List
from .workspace_webhook_counts import WorkspaceWebhookCounts
from .workspace_webhook_metrics_performance import WorkspaceWebhookMetricsPerformance
from .workspace_webhook_metrics_summary import WorkspaceWebhookMetricsSummary
from typing import Optional, Set
from typing_extensions import Self

class WorkspaceWebhookMetricsResponse(BaseModel):
    """
    Customer-facing webhook metrics, scoped to one workspace.  Deliberately carries no CloudWatch dashboard link and no cross-workspace aggregate — that data belongs to the staff-only /metrics endpoint.
    """ # noqa: E501
    summary: WorkspaceWebhookMetricsSummary
    performance: WorkspaceWebhookMetricsPerformance
    webhooks: WorkspaceWebhookCounts
    window_hours: StrictInt
    generated_at: datetime
    __properties: ClassVar[List[str]] = ["summary", "performance", "webhooks", "window_hours", "generated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkspaceWebhookMetricsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of summary
        if self.summary:
            _dict['summary'] = self.summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of performance
        if self.performance:
            _dict['performance'] = self.performance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of webhooks
        if self.webhooks:
            _dict['webhooks'] = self.webhooks.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkspaceWebhookMetricsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "summary": WorkspaceWebhookMetricsSummary.from_dict(obj["summary"]) if obj.get("summary") is not None else None,
            "performance": WorkspaceWebhookMetricsPerformance.from_dict(obj["performance"]) if obj.get("performance") is not None else None,
            "webhooks": WorkspaceWebhookCounts.from_dict(obj["webhooks"]) if obj.get("webhooks") is not None else None,
            "window_hours": obj.get("window_hours"),
            "generated_at": obj.get("generated_at")
        })
        return _obj


