# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Authenticated: 1,000 requests per hour (per API key, JWT, or session) - Anonymous: 100 requests per hour  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

    The version of the OpenAPI document: v1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from .recent_execution_out import RecentExecutionOut
from typing import Optional, Set
from typing_extensions import Self

class WorkflowStatisticsOut(BaseModel):
    """
    WorkflowStatisticsOut
    """ # noqa: E501
    total_executions: Optional[StrictInt] = 0
    successful_executions: Optional[StrictInt] = 0
    failed_executions: Optional[StrictInt] = 0
    running_executions: Optional[StrictInt] = 0
    cancelled_executions: Optional[StrictInt] = 0
    success_rate: Optional[Union[StrictFloat, StrictInt]] = 0.0
    average_duration_seconds: Optional[Union[StrictFloat, StrictInt]] = None
    recent_executions: Optional[List[RecentExecutionOut]] = None
    last_7_days: Optional[Dict[str, Any]] = None
    last_30_days: Optional[Dict[str, Any]] = None
    executions_by_day: Optional[List[Any]] = None
    common_errors: Optional[List[Any]] = None
    __properties: ClassVar[List[str]] = ["total_executions", "successful_executions", "failed_executions", "running_executions", "cancelled_executions", "success_rate", "average_duration_seconds", "recent_executions", "last_7_days", "last_30_days", "executions_by_day", "common_errors"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowStatisticsOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in recent_executions (list)
        _items = []
        if self.recent_executions:
            for _item_recent_executions in self.recent_executions:
                if _item_recent_executions:
                    _items.append(_item_recent_executions.to_dict())
            _dict['recent_executions'] = _items
        # set to None if average_duration_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.average_duration_seconds is None and "average_duration_seconds" in self.model_fields_set:
            _dict['average_duration_seconds'] = None

        # set to None if recent_executions (nullable) is None
        # and model_fields_set contains the field
        if self.recent_executions is None and "recent_executions" in self.model_fields_set:
            _dict['recent_executions'] = None

        # set to None if last_7_days (nullable) is None
        # and model_fields_set contains the field
        if self.last_7_days is None and "last_7_days" in self.model_fields_set:
            _dict['last_7_days'] = None

        # set to None if last_30_days (nullable) is None
        # and model_fields_set contains the field
        if self.last_30_days is None and "last_30_days" in self.model_fields_set:
            _dict['last_30_days'] = None

        # set to None if executions_by_day (nullable) is None
        # and model_fields_set contains the field
        if self.executions_by_day is None and "executions_by_day" in self.model_fields_set:
            _dict['executions_by_day'] = None

        # set to None if common_errors (nullable) is None
        # and model_fields_set contains the field
        if self.common_errors is None and "common_errors" in self.model_fields_set:
            _dict['common_errors'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowStatisticsOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total_executions": obj.get("total_executions") if obj.get("total_executions") is not None else 0,
            "successful_executions": obj.get("successful_executions") if obj.get("successful_executions") is not None else 0,
            "failed_executions": obj.get("failed_executions") if obj.get("failed_executions") is not None else 0,
            "running_executions": obj.get("running_executions") if obj.get("running_executions") is not None else 0,
            "cancelled_executions": obj.get("cancelled_executions") if obj.get("cancelled_executions") is not None else 0,
            "success_rate": obj.get("success_rate") if obj.get("success_rate") is not None else 0.0,
            "average_duration_seconds": obj.get("average_duration_seconds"),
            "recent_executions": [RecentExecutionOut.from_dict(_item) for _item in obj["recent_executions"]] if obj.get("recent_executions") is not None else None,
            "last_7_days": obj.get("last_7_days"),
            "last_30_days": obj.get("last_30_days"),
            "executions_by_day": obj.get("executions_by_day"),
            "common_errors": obj.get("common_errors")
        })
        return _obj


