# coding: utf-8

"""
    SpatialFlow API

    Real-time geospatial automation platform API.  ## Authentication  **API Key:** Include `X-API-Key` header **JWT Token:** Include `Authorization: Bearer <token>` header  ## Rate Limits  - Per API Key: 200 rps sustained, 1,000 rps burst - Per Organization: 1,000 rps aggregate  ## Webhook Verification  Outbound webhooks include HMAC-SHA256 signatures in `X-SF-Signature` header.  ## Support  - Documentation: https://docs.spatialflow.io - GitHub: https://github.com/spatialflow/spatialflow - Email: support@spatialflow.io     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from .workflow_step_retry_schema import WorkflowStepRetrySchema
from typing import Optional, Set
from typing_extensions import Self

class WorkflowRetryPolicyUpdateSchema(BaseModel):
    """
    Schema for updating retry policies for a workflow.
    """ # noqa: E501
    workflow_id: StrictStr
    default_retry_policy: Optional[StrictStr] = None
    step_overrides: Optional[List[WorkflowStepRetrySchema]] = None
    __properties: ClassVar[List[str]] = ["workflow_id", "default_retry_policy", "step_overrides"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowRetryPolicyUpdateSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in step_overrides (list)
        _items = []
        if self.step_overrides:
            for _item_step_overrides in self.step_overrides:
                if _item_step_overrides:
                    _items.append(_item_step_overrides.to_dict())
            _dict['step_overrides'] = _items
        # set to None if default_retry_policy (nullable) is None
        # and model_fields_set contains the field
        if self.default_retry_policy is None and "default_retry_policy" in self.model_fields_set:
            _dict['default_retry_policy'] = None

        # set to None if step_overrides (nullable) is None
        # and model_fields_set contains the field
        if self.step_overrides is None and "step_overrides" in self.model_fields_set:
            _dict['step_overrides'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowRetryPolicyUpdateSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workflow_id": obj.get("workflow_id"),
            "default_retry_policy": obj.get("default_retry_policy"),
            "step_overrides": [WorkflowStepRetrySchema.from_dict(_item) for _item in obj["step_overrides"]] if obj.get("step_overrides") is not None else None
        })
        return _obj


